add

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,1 +1,26 @@
 #!/usr/bin/env bash
+# Script to transfer a file from client to server using scp
+
+# Check if the correct number of parameters are provided
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+FILE_PATH="$1"
+SERVER_IP="$2"
+USERNAME="$3"
+SSH_KEY="$4"
+
+# Transfer file using scp with strict host key checking disabled
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
+
+
+# Check if scp command was successful
+if [ $? -eq 0 ]; then
+    echo "$FILE_PATH transferred successfully to $USERNAME@$SERVER_IP:~/"
+else
+    echo "Error transferring $FILE_PATH to $USERNAME@$SERVER_IP"
+fi
+
